// <auto-generated />
using System;
using MealPlannerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlannerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403141627_AddPlannerQuestionnairePreferences")]
    partial class AddPlannerQuestionnairePreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MealPlannerApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 165,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 130,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 155,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 402,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cheddar Cheese"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 389,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rolled Oats"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 59,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Greek Yogurt"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 89,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 208,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Salmon Fillet"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 86,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sweet Potato"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 164,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cherry Tomatoes"
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 149,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 431,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bell Pepper"
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 40,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 149,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 884,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 21,
                            CaloriesPer100g = 160,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Avocado"
                        });
                });

            modelBuilder.Entity("MealPlannerApp.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PortionMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlanTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("MealPlanTemplates");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlanTemplateMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealPlanTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PortionMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanTemplateId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlanTemplateMeals");
                });

            modelBuilder.Entity("MealPlannerApp.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookingTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 2,
                            Calories = 520,
                            CookingTime = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic high-protein plate with grilled chicken, rice, and broccoli.",
                            Instructions = "1. Cook the rice until fluffy and set it aside.\n2. Heat a pan, add the chicken breast, and cook until golden on both sides and fully cooked through.\r\n3. Steam or saute the broccoli until just tender.\r\n4. Slice the chicken and plate it with the rice and broccoli.\r\n5. Serve everything warm.",
                            IsVegetarian = false,
                            Name = "Grilled Chicken and Rice",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 2,
                            Calories = 390,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fast vegetarian bowl with rice, broccoli, and melted cheddar.",
                            Instructions = "1. Cook the rice and keep it warm.\r\n2. Steam the broccoli until bright green and tender.\r\n3. Put the rice into a bowl and top it with the broccoli.\r\n4. Sprinkle cheddar cheese over the hot bowl so it softens slightly.\r\n5. Serve immediately.",
                            IsVegetarian = true,
                            Name = "Broccoli Rice Bowl",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = 2,
                            Calories = 410,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A quick savory breakfast with eggs, spinach, cheese, and onion.",
                            Instructions = "1. Heat olive oil in a non-stick pan and soften the onion for a few minutes.\r\n2. Add the spinach and cook until wilted.\r\n3. Beat the eggs, pour them into the pan, and let them begin to set.\r\n4. Sprinkle cheddar over the top and fold the omelette in half.\r\n5. Cook for another minute, then slide onto a plate and serve.",
                            IsVegetarian = true,
                            Name = "Spinach Omelette",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 4,
                            ApprovalStatus = 2,
                            Calories = 360,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A no-cook breakfast bowl with oats, yogurt, and banana.",
                            Instructions = "1. Spoon the Greek yogurt into a bowl.\r\n2. Stir in the rolled oats so they soften slightly.\r\n3. Slice the banana and place it on top.\r\n4. Let the bowl rest for a couple of minutes before serving.",
                            IsVegetarian = true,
                            Name = "Greek Yogurt Banana Oats",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 5,
                            ApprovalStatus = 2,
                            Calories = 610,
                            CookingTime = 40,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An easy oven meal with salmon, sweet potato, broccoli, and garlic.",
                            Instructions = "1. Cut the sweet potato into cubes and place it on a baking tray with olive oil and garlic.\r\n2. Roast the sweet potato until it starts to soften.\r\n3. Add the salmon and broccoli to the tray.\r\n4. Bake until the salmon flakes easily and the broccoli is tender.\r\n5. Serve straight from the tray while hot.",
                            IsVegetarian = false,
                            Name = "Salmon and Sweet Potato Tray Bake",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 6,
                            ApprovalStatus = 2,
                            Calories = 560,
                            CookingTime = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A hearty vegetarian pasta with chickpeas, tomatoes, spinach, and parmesan.",
                            Instructions = "1. Cook the pasta until al dente and reserve a little cooking water.\r\n2. In a pan, warm olive oil and garlic, then add the cherry tomatoes.\r\n3. Stir in the chickpeas and cook until heated through.\r\n4. Add spinach and cook until wilted, then fold in the pasta.\r\n5. Finish with parmesan and a splash of pasta water if needed before serving.",
                            IsVegetarian = true,
                            Name = "Chickpea Tomato Pasta",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 7,
                            ApprovalStatus = 2,
                            Calories = 545,
                            CookingTime = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A one-pan chicken and rice meal with peppers, onion, and garlic.",
                            Instructions = "1. Cook the rice first and set it aside.\r\n2. Saute onion, bell pepper, and garlic in olive oil until softened.\r\n3. Add the chicken pieces and cook until lightly browned and cooked through.\r\n4. Stir the rice into the pan and mix everything together until hot.\r\n5. Serve the skillet meal straight away.",
                            IsVegetarian = false,
                            Name = "Chicken Pepper Rice Skillet",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 8,
                            ApprovalStatus = 2,
                            Calories = 430,
                            CookingTime = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fresh no-cook salad with chickpeas, cucumber, tomatoes, and avocado.",
                            Instructions = "1. Drain the chickpeas and add them to a large bowl.\r\n2. Dice the cucumber, halve the cherry tomatoes, and cube the avocado.\r\n3. Add everything to the bowl with olive oil.\r\n4. Toss gently so the avocado stays mostly intact.\r\n5. Serve chilled or at room temperature.",
                            IsVegetarian = true,
                            Name = "Mediterranean Chickpea Salad",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("MealPlannerApp.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityInGrams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "IngredientId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 1,
                            QuantityInGrams = 200,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 2,
                            QuantityInGrams = 150,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 3,
                            QuantityInGrams = 120,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 2,
                            QuantityInGrams = 150,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 3,
                            QuantityInGrams = 180,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 6,
                            QuantityInGrams = 30,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 4,
                            QuantityInGrams = 180,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 5,
                            QuantityInGrams = 60,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 6,
                            QuantityInGrams = 30,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 17,
                            QuantityInGrams = 30,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 19,
                            QuantityInGrams = 10,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 8,
                            QuantityInGrams = 200,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 7,
                            QuantityInGrams = 60,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 9,
                            QuantityInGrams = 120,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 10,
                            QuantityInGrams = 180,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 11,
                            QuantityInGrams = 250,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 3,
                            QuantityInGrams = 120,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 18,
                            QuantityInGrams = 10,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 19,
                            QuantityInGrams = 15,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 14,
                            QuantityInGrams = 180,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 12,
                            QuantityInGrams = 160,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 13,
                            QuantityInGrams = 180,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 5,
                            QuantityInGrams = 60,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 15,
                            QuantityInGrams = 25,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 18,
                            QuantityInGrams = 10,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 19,
                            QuantityInGrams = 10,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 1,
                            QuantityInGrams = 180,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 2,
                            QuantityInGrams = 160,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 16,
                            QuantityInGrams = 120,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 17,
                            QuantityInGrams = 60,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 18,
                            QuantityInGrams = 10,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 19,
                            QuantityInGrams = 10,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 12,
                            QuantityInGrams = 180,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 20,
                            QuantityInGrams = 120,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 13,
                            QuantityInGrams = 120,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 21,
                            QuantityInGrams = 80,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 19,
                            QuantityInGrams = 10,
                            RecipeId = 8
                        });
                });

            modelBuilder.Entity("MealPlannerApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BodyWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(70.0);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludedFoods")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredMealsPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BodyWeightKg = 70.0,
                            ConcurrencyStamp = "c3e1c75f-159f-4e2d-a2eb-8b67800fc86f",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@mealplanner.local",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@MEALPLANNER.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PhoneNumberConfirmed = false,
                            PreferredMealsPerDay = 3,
                            Role = 0,
                            SecurityStamp = "d6420f08-9b3e-4c53-bf64-cf9afc6ec3d8",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MealPlannerApp.Models.Meal", b =>
                {
                    b.HasOne("MealPlannerApp.Models.MealPlan", "MealPlan")
                        .WithMany("Meals")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApp.Models.Recipe", "Recipe")
                        .WithMany("Meals")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlan", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlanTemplate", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", "Owner")
                        .WithMany("MealPlanTemplates")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlanTemplateMeal", b =>
                {
                    b.HasOne("MealPlannerApp.Models.MealPlanTemplate", "MealPlanTemplate")
                        .WithMany("Meals")
                        .HasForeignKey("MealPlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApp.Models.Recipe", "Recipe")
                        .WithMany("MealPlanTemplateMeals")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlanTemplate");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlannerApp.Models.Recipe", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", "Owner")
                        .WithMany("Recipes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MealPlannerApp.Models.RecipeIngredient", b =>
                {
                    b.HasOne("MealPlannerApp.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApp.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MealPlannerApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealPlannerApp.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MealPlannerApp.Models.MealPlanTemplate", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MealPlannerApp.Models.Recipe", b =>
                {
                    b.Navigation("MealPlanTemplateMeals");

                    b.Navigation("Meals");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealPlannerApp.Models.User", b =>
                {
                    b.Navigation("MealPlanTemplates");

                    b.Navigation("MealPlans");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
